---

plugins: [flowtype]

parser: babel-eslint

parserOptions:
  ecmaVersion: 2017
  sourceType: module

extends:
  - 'airbnb/base'
  - plugin:import/errors
  - plugin:import/warnings

env:
  amd: true
  browser: true
  es6: true
  node: true
  jest: true
