language: node_js
node_js:
  - "node"

script:
  make lint test

addons:
  code_climate:
    repo_token: CCTOKEN

after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < lcov.info
